/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cash2;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import java.util.ArrayList;

/**
 *
 * @author Андрей
 */
public class Graphic extends javax.swing.JFrame {

    /**
     * Creates new form Graphic
     */
    ArrayList<String> dates = new ArrayList<String>();
    ArrayList<String> sums = new ArrayList<String>();

    public Graphic() {
        initComponents();
    }

    public Graphic(String month, int year, ArrayList<String> date, ArrayList<String> sum) {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        setTitle("Касса за " + month + "," + year);
        dates = date;
        sums = sum;
        pack();
        repaint();
        setVisible(true);
    }

    public void paint(Graphics g) {
        super.paint(g);
        //g.setColor(Color.BLACK);
        int maxX = dates.size() * 32 + 18;
        int minX = 50;
        int maxY = 475;
        int minY = 45;
        //g.drawLine(minX, minY, minX, maxY);
        g.drawLine(minX, maxY, maxX, maxY);
        int xd = minX;

        /*Draw dates and vertical lines*/
        for (int i = 0; i < dates.size(); i++) {
            g.drawString(dates.get(i), xd - 7, maxY + 15);
            g.drawLine(xd, maxY, xd, minY + 10);
            xd += 32;
        }

        Float min = min_sum();
        Integer max = (int) max_sum();

        float kx = (maxX - 50) / (dates.size() - 1);
        float dy = (max - min) / 13;
        float ky = 390 /(max-min);

        float py;
        float py2;
        float px;
        float px2;

        Graphics2D g2 = (Graphics2D) g;
        int xs = minX - 35;
        int ys = maxY - 25;

        for (int i = 0; i < 14; i++) {
            g.drawString(int_str(min), xs, ys);
            ys -= 30;
            min += dy;
            g.drawLine(minX, ys + 25, maxX, ys + 25);
        }

        for (int i = 0; i < sums.size() - 1; i++) {
            py = (max - Integer.parseInt(sums.get(i)))* ky + 55;
            py2 = (max - Integer.parseInt(sums.get(i + 1)))* ky + 55;
            px = i * kx + 50;
            px2 = (i + 1) * kx + 50;
            g2.draw(new Line2D.Double(px, py, px2, py2));

        }

    }

    float max_sum() {
        float max = 0;
        float n = 0;
        for (int i = 0; i < sums.size(); i++) {
            max = Integer.parseInt(sums.get(i));
            if (n > max) {
                max = n;
            }
            n = max;
        }
        return max;
    }

    float min_sum() {
        float min = 0;
        float m = Float.valueOf(sums.get(0));
        for (int i = 0; i < sums.size(); i++) {
            min = Integer.parseInt(sums.get(i));
            if (min > m) {
                min = m;
            }
            m = min;
        }
        return min;
    }

    String int_str(float min) {
        Integer n = (int) min;
        String m = n.toString();
        return m;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Graphic().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
